apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-zknfnpse
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-zknfnpse:af21b7247c33ac8b56d746c587970c6d26fa477e@sha256:53801468ef84e297791e68ec180d943074048f9b3e5ec81b6e0ab0f85fa302b6
        name: container-image  
